### ISSUE TITLE
draft.js file should be ignored

### ISSUE THREAD

**Issue by midrissi** [fredGandelot/waktrello#12]
The [`draft.js`](https://github.com/fredGandelot/waktrello/blob/master/TrelloVDC/draft.js) file contains sensitive data (an [`app key`](https://github.com/fredGandelot/waktrello/blob/master/TrelloVDC/draft.js#L8) and a [`token`](https://github.com/fredGandelot/waktrello/blob/master/TrelloVDC/draft.js#L9)) so it should be ignored or simply put the `credentials` to [`env vars`](http://livedoc.wakanda.org/Utilities/Process/env.303-1101637.en.html)

**Comment by OELBOUHASSANI** [comment]
@midrissi done , thank you  :)
